name: "Validate OCPI OpenAPI specification"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "**.md"

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - "**.md"

jobs:
  validate-oicp-v230-specification:
    name: "Validate the OICP 2.3.0 OpenAPI specification"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swagger Editor Validator
        uses: char0n/swagger-editor-validate@v1.3.2
        with:
          definition-file: ./2.3.0/api/2.3.0.spec.yml

  fmt:
    name: Format Go code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Download Go modules
        run: |
          cd 2.3.0
          go mod download

      - name: Format Go code
        run: go fmt ./2.3.0/...
